spring:
  application:
    name: BJJ Calendar

geoapify:
  api-key: ${GEOAPIFY_API_KEY}
  polling-interval-ms: 1000
  max-polling-attempts: 30

teamup:
  api:
    enabled: true
    url: https://api.teamup.com
    email: ${TEAMUP_EMAIL}
    password: ${TEAMUP_PASSWORD}
    token: ${TEAMUP_TOKEN}
    calendar-id: ezm6tf
    app-name: ${spring.application.name}

sources:
  timeout: 20
  city-overrides:
    "Petit-lancy": "Geneva"
    "Barueri": "São Paulo"
  ibjjf:
    enabled: false
    regions:
      - Europe
    championshipTypes:
      - World Adult
      - World Master
      - World NoGi
      - Brasileiro
    base-url: https://ibjjf.com
    calendar-page: /events/calendar
    calendar-json: /api/v1/events/calendar.json
    etag-file: target/cache/ibjjf_calendar_etag.txt
  ajp:
    enabled: true
    calendar-pattern: https://ajptour.com/en/events-1/events-calendar-%s
    events:
      - Grand Slam
      - World
    countries:
      - lu
      - fr
      - be
      - de
      - nl
      - ch
      - it
      - es
      - uk
      - pt
      - tr
  cfjjb:
    enabled: false
    base-url: https://cfjjb.com
    calendar-page: /competitions/calendrier-competitions
    excludes:
      - IBJJF
      - Festival
  smoothcomp:
    enabled: false
    url: https://smoothcomp.com/en/events/upcoming
    grappling-industries-url: https://grapplingindustries.smoothcomp.com
    naga-url: https://naga.smoothcomp.com
    other-urls:
      - https://agf.smoothcomp.com
    countries:
      - lu
      - fr
      - be
      - de
      - nl
      - ch
    distance-filter-enabled: true
    max-distance: 150
    origin-latitude: 49.6117
    origin-longitude: 6.1300
